version: '3'

services:
  frontend:
    build:
      context: ./front-end
    expose:
      - "80"
    networks:
      - app-network

  backend:
    build:
      context: ./back-end
    expose:
      - "5000"
    networks:
      - app-network

  proxy:
    build: ./proxy
    ports:
      - "50003:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge